# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Delete old zip file
        uses: mknejp/delete-release-assets@v1
        with:
          assets: 'TRP.zip' # Globs or specific names of assets to delete
          tag: '1.1.0' # The tag of the release to modify
          token: ${{ secrets.TRP_WORKFLOW }} # Required for authentication

      # Create zip file
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: 'TRP.zip'
          exclusions: '.gitattributes .gitignore /.git*'

      - name: Add zip to release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.TRP_WORKFLOW }}
          tag_name: '1.1.0'
          files: 'TRP.zip'
          fail_on_unmatched_files: false

      # create a version string
      - name: calculate version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v2
        with:
          # Main branch for the repository
          main_branch: master
          # First version, defaults to 1.0.0
          initial_version: 1.69.1

      - name: Use version
        run: 'echo "Calculated version: ${{ steps.calculate-version.outputs.version-string }}"'

      - name: Modrinth Publish
        uses: cloudnode-pro/modrinth-publish@v2.1.4
        with:
          token: ${{ secrets.MODRINTH_TOKEN }} # Modrinth API token
          project: 'ZMrb9fWk' #  ID of the project this version is for
          name: "TARDIS Resource Pack"
          version: ${{ steps.calculate-version.outputs.version-string }}
          # mod loaders that this version supports
          loaders: |-
            minecraft
          # list of versions of Minecraft that this version supports
          game-versions: |-
            1.21.10
          # list of file paths to upload
          files: |-
            TRP.zip
